import type { Metadata, Viewport } from "next";
import { Overpass, Overpass_Mono } from "next/font/google";
import "./globals.css";
import TabBar from "@/components/TabBar";

const overpass = Overpass({
  variable: "--font-overpass",
  subsets: ["latin"],
  weight: ["300", "400", "600", "700", "800"],
});

const overpassMono = Overpass_Mono({
  variable: "--font-overpass-mono",
  subsets: ["latin"],
  weight: ["400", "600"],
});

export const metadata: Metadata = {
  title: "Is My Train Running?",
  description:
    "Melbourne train disruptions without the confusion. See which lines are running right now, at any future time, or by station calendar.",
  manifest: "/manifest.webmanifest",
  appleWebApp: { capable: true, title: "Is My Train Running?", statusBarStyle: "default" },
  // app/favicon.ico is linked by Next's file convention; these add the vector
  // icon browsers prefer when they support it, and the iOS home-screen icon.
  // All are generated by scripts/build_brand.ts.
  icons: {
    icon: [{ url: "/icon.svg", type: "image/svg+xml" }],
    apple: [{ url: "/apple-touch-icon.png", sizes: "180x180" }],
  },
};

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#fbf9f3",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${overpass.variable} ${overpassMono.variable} h-full antialiased`}>
      <body className="h-dvh flex flex-col bg-bg text-ink">
        <main className="flex-1 min-h-0 flex flex-col">{children}</main>
        <TabBar />
      </body>
    </html>
  );
}
