import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "Is My Train Running?",
    short_name: "My Train?",
    description: "Melbourne train disruptions without the confusion.",
    start_url: "/",
    display: "standalone",
    background_color: "#f3efe4",
    theme_color: "#fbf9f3",
    // Generated by scripts/build_brand.ts. The maskable entry is a separate
    // file, not a `purpose: "any maskable"` on the others: platforms crop
    // maskable icons to a circle, and the rounded tile the others use would
    // lose its corners to it.
    icons: [
      { src: "/icon.svg", sizes: "any", type: "image/svg+xml" },
      { src: "/icon-192.png", sizes: "192x192", type: "image/png" },
      { src: "/icon-512.png", sizes: "512x512", type: "image/png" },
      { src: "/icon-maskable-512.png", sizes: "512x512", type: "image/png", purpose: "maskable" },
    ],
  };
}
